# Generated by Django 4.2.27 on 2026-01-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='party_size',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
